'use client'

import React, { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Wand2, Copy, Sparkles, FileText, Mail, Heart, RefreshCw } from 'lucide-react'

const tools = [
  {
    id: 'deal-notes',
    name: 'Deal Notes Specialist',
    description: 'Transform complex mortgage details into clear, professional summaries',
    icon: FileText,
    color: 'bg-blue-100 text-blue-600',
    placeholder: 'Enter deal details here (property info, financing terms, conditions, etc.)...',
    promptPrefix: 'Create professional deal notes for the following mortgage transaction:',
  },
  {
    id: 'content-coach',
    name: 'Content Coach',
    description: 'Generate engaging social media posts and marketing content',
    icon: Sparkles,
    color: 'bg-purple-100 text-purple-600',
    placeholder: 'What would you like to create content about? (e.g., first-time homebuyers, rate changes, market updates...)',
    promptPrefix: 'Create engaging marketing content about:',
  },
  {
    id: 'renewal-email',
    name: 'Renewal Email Builder',
    description: 'Craft personalized renewal outreach emails for clients',
    icon: Mail,
    color: 'bg-green-100 text-green-600',
    placeholder: 'Enter client details (name, current rate, renewal date, relationship notes...)...',
    promptPrefix: 'Write a personalized mortgage renewal email for:',
  },
  {
    id: 'thank-you',
    name: 'Thank You Note',
    description: 'Generate heartfelt thank you notes for clients and referral partners',
    icon: Heart,
    color: 'bg-pink-100 text-pink-600',
    placeholder: 'Enter recipient details and the occasion (closing, referral, anniversary...)...',
    promptPrefix: 'Write a heartfelt thank you note for:',
  },
]

export default function AgentToolsPage() {
  const [activeTool, setActiveTool] = useState('deal-notes')
  const [input, setInput] = useState('')
  const [output, setOutput] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [tone, setTone] = useState('professional')

  const currentTool = tools.find((t) => t.id === activeTool) || tools[0]

  const handleGenerate = async () => {
    if (!input.trim()) return

    setIsGenerating(true)
    setOutput('')

    // Simulate AI generation (in production, this would call OpenAI API via your backend)
    try {
      // This would be an API call to your backend which calls OpenAI
      // const response = await fetch('/api/generate', {
      //   method: 'POST',
      //   body: JSON.stringify({ tool: activeTool, input, tone }),
      // })
      // const data = await response.json()
      // setOutput(data.content)

      // Simulated response for demo
      await new Promise((resolve) => setTimeout(resolve, 2000))
      setOutput(
        `[AI Generated ${currentTool.name} Content]\n\nBased on your input, here's a ${tone} response:\n\n${input}\n\n---\n\nThis is a placeholder. In production, this would be generated by the OpenAI API based on the ${currentTool.name} tool settings.`
      )
    } catch (error) {
      console.error('Generation failed:', error)
      setOutput('Failed to generate content. Please try again.')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(output)
  }

  const handleRegenerate = () => {
    handleGenerate()
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">AI Tools</h1>
        <p className="text-gray-500 mt-1">
          Use AI-powered tools to create professional content quickly
        </p>
      </div>

      {/* Tool Selection */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {tools.map((tool) => {
          const Icon = tool.icon
          const isActive = activeTool === tool.id
          return (
            <Card
              key={tool.id}
              className={`cursor-pointer transition-all ${
                isActive
                  ? 'ring-2 ring-blue-500 border-blue-500'
                  : 'hover:border-gray-300'
              }`}
              onClick={() => {
                setActiveTool(tool.id)
                setInput('')
                setOutput('')
              }}
            >
              <CardContent className="p-4">
                <div className={`h-10 w-10 rounded-lg ${tool.color} flex items-center justify-center mb-3`}>
                  <Icon className="h-5 w-5" />
                </div>
                <h3 className="font-medium text-gray-900">{tool.name}</h3>
                <p className="text-sm text-gray-500 mt-1">{tool.description}</p>
              </CardContent>
            </Card>
          )
        })}
      </div>

      {/* Tool Interface */}
      <div className="grid gap-6 lg:grid-cols-2">
        {/* Input */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <currentTool.icon className="h-5 w-5" />
              {currentTool.name}
            </CardTitle>
            <CardDescription>{currentTool.description}</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label>Tone</Label>
              <Select value={tone} onValueChange={setTone}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="professional">Professional</SelectItem>
                  <SelectItem value="friendly">Friendly</SelectItem>
                  <SelectItem value="casual">Casual</SelectItem>
                  <SelectItem value="formal">Formal</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Your Input</Label>
              <Textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder={currentTool.placeholder}
                rows={8}
              />
            </div>

            <Button
              onClick={handleGenerate}
              disabled={isGenerating || !input.trim()}
              className="w-full"
            >
              <Wand2 className="h-4 w-4 mr-2" />
              {isGenerating ? 'Generating...' : 'Generate'}
            </Button>
          </CardContent>
        </Card>

        {/* Output */}
        <Card>
          <CardHeader>
            <CardTitle>Generated Content</CardTitle>
            <CardDescription>
              Review and copy the generated content
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="min-h-[300px] p-4 bg-gray-50 rounded-lg border">
              {isGenerating ? (
                <div className="flex items-center justify-center h-full">
                  <div className="text-center">
                    <div className="h-8 w-8 border-2 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto mb-2" />
                    <p className="text-sm text-gray-500">Generating content...</p>
                  </div>
                </div>
              ) : output ? (
                <pre className="whitespace-pre-wrap text-sm text-gray-700 font-sans">
                  {output}
                </pre>
              ) : (
                <div className="flex items-center justify-center h-full text-gray-400">
                  <p>Generated content will appear here</p>
                </div>
              )}
            </div>

            {output && !isGenerating && (
              <div className="flex gap-2">
                <Button onClick={handleCopy} variant="outline" className="flex-1">
                  <Copy className="h-4 w-4 mr-2" />
                  Copy to Clipboard
                </Button>
                <Button onClick={handleRegenerate} variant="outline">
                  <RefreshCw className="h-4 w-4 mr-2" />
                  Regenerate
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
